### PR TITLE
Updating OOMMF to 2.0a1 verison

### PR DESCRIPTION
**Pull request by sergii-mamedov**
An update of the 'oommf' folder to the latest 2.0a1 version, following the update script

### CODE REVIEW

**Comment by fangohr** [comment]
Good, thank you.

We also need to update `versionlog.txt` and `oommf-version`.

This should happen automatically when you use the `Makefile-update-oommf` file via 

`make -f Makefile-update-oommf all`. 

There are also some manual steps required - check the `Makefile-update-oommf` for details.

**Comment by sergii-mamedov** [comment]
Thank for your comment, I will fix it tomorrow

**Comment by minrk** [comment]
Can 2.0a1 get a tag on GitHub so there's a release?

**Comment by marijanbeg** [comment]
Hi @minrk, it is released now. Thank you for your help.

**Pull request merged**
