### PR TITLE
Added three DMI fields that work with PBCs

### PR DESCRIPTION
**Pull request by davidcortesortuno**
Added `T`, `C_nv` and `D_2d` symmetry class DMI to the `local` folder with OOMMF extensions. These modules work with periodic boundaries, thus it is not necessary to call a separate field class when using/not using PBCs.

### CODE REVIEW

**Comment by fangohr** [comment]
Thank you for the contribution.

I didn't want this repository to become a place to add extensions to OOMMF. On the other hand, I can see that this is convenient, and github helps us to make this easy.

I think it is important to separate what comes with OOMMF, and what are user contributions, and by putting your files in the oxs/local folder, you do this as much as possible.

What we need before this can be merged are (at least) three examples (=mif files): one for every interaction that users can run to (i) get a feeling for the interface, and (ii) see an example with parameters that give sensible results. Sensible here might mean parameters that lead to skyrmion formation. Could you add those, please? I have seen that other extension modules provide example files in the same folder. I suggest to use naming for them if files that starts with the same root filename as the source files (or the class name).

Ideally, I would like to have a test for each example (maybe additional python script that executes the mif file, then checks some properties in the computed solution, and confirms pass or fail accordingly). 

One more question: How do these files relate to the bulk dmi module that Marijan (@marijanbeg) has developed? Does it replace it (and provides PBC?)?

**Comment by davidcortesortuno** [comment]
Ah yes, I have some examples that I used for testing. I will add them soon

> One more question: How do these files relate to the bulk dmi module that Marijan (@marijanbeg) has developed? Does it replace it (and provides PBC?)?

Yes, it replaces that file to make the names more consistent and make the files work with PBCs. I also fixed the chirality according to the finite difference discretisation (In Rohart's paper for example, the sign is wrong between what they show in their paper and the module they created for OOMMF). For the names I use the symmetry class conventions, `DMI_T`, `DMI_Cnv` and `DMI_D2d`. It's better if someone wants to add new DMI modules later.

**Comment by fangohr** [comment]
@marijanbeg - do you think this is ready to merge? 

Questions I see are:
- what about the minus sign in the bulk dmi
- what if somebody uses the old 'bulk dmi' module and now has the new OOMMF? Not a disasters if this breaks (not so many users at the moment) but if we can avoid it, should we? (Maybe we have already?)
- Is OOMMFC up-to-date or likely to be updated soon?

If so, can you merge (either you or David), and then update the container image on docker hub? I'd like to see if the chain works if somebody else other than me does it.

(would also be good to resolve https://github.com/fangohr/oommf/issues/6 so we have more confidence in running our CI - although it probably makes no difference here as we don't actually exercise the new code in the CI build anyway.)

**Comment by marijanbeg** [comment]
I think before we proceed with tests and examples, we should address what are we trying to have. Here are the answers to @fangohr questions:

- The interfacial DMI (written by Rohart) is already a part of official OOMMF release (with the minus sign). In the bulk DMI extension I wrote, I kept the same sign to make it consistent with interfacial DMI. I can agree this minus sign might be wrong, but we also know that some people write w_dmi = D.(Si x Sj) while others write w_dmi = -D.(Si x Sj). I have not checked the consistency of interfacial DMI extension with their (Rohart and Thiaville) paper, but I know they use the negative D in their paper. @davidcortesortuno, are you sure that with minus sign you get the wrong chirality? Are you suggesting we should offer two new DMI extensions (bulk and "antiskyrmion") as well as replace the already existing interfacial DMI. I am happy with adding those terms, but a bit sceptical with replacing the already existing one (in official OOMMF release). We must have in mind a lot of people use it. I do not feel very comfortable with just changing the existing OOMMF (interfacial dmi) code in this repository - but I might be wrong.

- If somebody runs joommf with new oommf (+ new DMI extensions), then nothing will work because @davidcortesortuno now renamed the classes. It also would not work with existing interfacial DMI because it has a new name. The changes in OOMMFC that should be done are very minor and easy to do, but I prefer not to do them until we agree on how to proceed. 

- OOMMFC supports interfacial and bulk DMI. Adding the third term should be easy.

**Comment by marijanbeg** [comment]
Also we should have in mind that OOMMF from this repository can only be installed on Linux and MacOS. Most people (Windows users) will install it from the website.

**Comment by davidcortesortuno** [comment]
Hi, I understand your points. It's a bit tricky to change the already implemented classes. What I don't like from the existing modules are the names. For example, the interfacial DMI class is named according to exchange class with 6 ngbrs, but interfacial only works 4 ngbs and `DMExchange` is too generic. Also, this class is not only for interfacial systems but rather for general `Cnv` symmetry class materials. Same with `Bulk` , because you can have multiple bulk materials wit different DMI. I understand that interfacial or bulk are popular right now but that's while other DMI materials aren't discovered yet. Thus, a more consistent name like `DMI_XXX` is, to my point of view, more clear.

I agree with @marijanbeg that the sign/chirality is not significantly important. I was just trying to make the files consistent with the definitions of the std problem paper. I'm mostly worried about the class names.

The problem now is that we are not the OOMMF code main developers so it's difficult to change the classes. I really don't know how to proceed. An option would be just to use my forked repos in the standard problem paper repository.

And sorry @marijanbeg for deleting the Bulk DMI from @fangohr OOMMF repo, but I can include it back :) . I just updated the repo to the latest OOMMF version.

**Comment by marijanbeg** [comment]
I agree with you @davidcortesortuno that new names you gave to the classes are much better and that the sign in all extensions should be right. Ideally, we would like to have them all three (with the right sign and sensible names) in official OOMMF release but that is not possible.

The problem I have is that JOOMMF should work for any installation of OOMMF, which if we modify the interfacial DMI code (by Rohart) is not possible. Also, it feels a bit like stealing the credit (and future citations) from the original authors.

**Comment by marijanbeg** [comment]
We also have https://github.com/joommf/oommf-bulk-dmi repository where the bulk DMI extension is. It would also be tidier if we treat our code as "extensions" and provide them in a separate repository. For convenience, we can ad them to this repo as well.

**Comment by marijanbeg** [comment]
For that we can create a new repository (e.g. `joommf/oommf-dmi`) where we will put and document all extensions with explanations on how to install them.

P.S. I would be also happy for this repository to be under your (@davidcortesortuno) name since you did some crucial extensions and corrections.

**Comment by fangohr** [comment]
Yes, I also thought we should have each OOMMF extension in a separate repository (and we should in fact version them, and create a Zenodo DOI for it, and the offer a way for people to cite them, and also put a document in the repo that contains the equations -- all the normal stuff we would expect to see in an ideal world).

**Comment by davidcortesortuno** [comment]
Nice, sounds good. Are we using the `joommf` repositories or mine?

**Comment by fangohr** [comment]
I'd be happy to use yours as this is your code - although it would be helpful if you kept the account alive and don't rename the repositories in the foreseeable future (20 to 50 years?).

**Comment by marijanbeg** [comment]
The cleanest solution then might be to use `joommf` organisation since bulk DMI is already there. In that repository, we can easily state what was David's contribution.

**Comment by marijanbeg** [comment]
Here are some points I discussed with Hans and David so we have it in writing:

- The best way to proceed would be not to replace the already existing interfacial DMI extension in OOMMF.
- In addition to that extension, we will add three new ones. This is to make sure that all people who use the existing DMI extension in OOMMF can still run simulations.
- The new DMI modules will have names as David sugessted
- We need a separate repository for each extension
- OOMMFC interface will follow that and provide access to 3+1=4 DMI extensions
- To make sure we are right about the sign, we will contact Rohart and Thiaville.
   - They have negative value of D in their paper for Fe, but they use Co (D>0)
   - When their (OOMMF) simulations are compared with fidimag and mumax, they have different chiralities. The same is true when compared to the analytic model. It is not clear how they did the fitting in their paper then.
    - We will mention we now have periodic boundary conditions and two new modules.

@davidcortesortuno, do you want to add/change anything on this list and are the arguments for the wrong sign ok with you?

**Comment by davidcortesortuno** [comment]
@marijanbeg the arguments seem ok to me. MuMax3 has the right sign as well, as you mention http://aip.scitation.org/doi/full/10.1063/1.4899186 , so their paper is consistent with their code.

I don't think a separate repo for each extension is necessary, it would make people confuse about which repo to cite with 3 different Zenodo DOIs. And we are only adding DMI calculation classes. It also complicates things because we would repeat the same structure for each repo.

**Comment by marijanbeg** [comment]
Hi @davidcortesortuno, we still have no answer from Rohart and Thiaville, but we are fairly confident the sign is wrong.

1. Are all 3 extensions you added here up to date - most recent versions as we have in joommf/oommf-dmi repo?
2. As I understand, you replaced the Rohart and Thiaville DMI extension with yours. If that is true, could you please put it back, so that we have: their extension +  3 our extensions.

I guess we can then merge this pull request and update OOMMF conda package.

**Comment by marijanbeg** [comment]
Also, can you please make sure everything compiles on your machine.

**Comment by davidcortesortuno** [comment]
Hi @marijanbeg  I was going to close this PR since I came up with a better solution by creating a `Makefile` that copies the new DMI modules into this repository. However I cannot push my branch into this repo and make another PR since I don;t have access. I think I'll wait for Hans reply

**Comment by fangohr** [comment]
Hi David, just had another review of this with Marijan. I insist on three repositories for the three new interactions for various reasons, including the ability to version and develop them further individually. Marijan will restructure this repo to clone from those repos to then build OOMMF with the extension. This way we keep a 'vanilla' OOMMF in this repository, but allow people to use the extensions.
Having to cite different URL/Zenodo DOI for each extension is no problem I think as often people will just use one of them. Does that work for you?

**Comment by marijanbeg** [comment]
Hi @davidcortesortuno, is there anything in this pull request (that I cannot see) which is not related to the DMI extensions and you want to be included in this repository? If no, I would close this pull request because:

1. We are going to have three separate repositories for each DMI extension in JOOMMF organisation.
2. Makefile in this repository will have a target that pulls those extensions and compiles OOMMF.

**Comment by davidcortesortuno** [comment]
Yes, just close this PR. The DMI modules are updated in the new `oommf-dmi` repo

**Comment by marijanbeg** [comment]
Since we all agreed on how to proceed with this, I close this pull request.

**Pull request closed without merging**
